### ISSUE TITLE
Highlight certain customers

### ISSUE THREAD

**Issue by skjerns** [leih-lokal/LeihLokalVerwaltung#100]
It would be be able to display notes when entering certain customers, e.g. if someone forgot to sign the rental agreement, it can be highlighted in red the next time the person makes a rental. same goes for remarks for people, e.g. if we decide to block someone.

Until now this was solved by adding e.g. "AUSWEIS" to their last name, such that the next person typing "923" will get the name "Mustermann AUSWEIS" as a name. Maybe we can solve this differently?

**Comment by daniel17903** [comment]
I think we also have these issues when someone forgets to insert any required data for new rentals / customers / items. Therefore we could build some kind of notification system. This would include a notification symbol in the upper right corner where the user could expand a list of all notifications (e.g. "Missing Mail / Ausweis / Date / ... for User / Rental / Item x"). This way we would have an overview of all missing data.

We could also create a notifications for failed Woocommerce updates. This is important so that we can retry them or do the changes in Woocommerce manually.

As you suggested we could display these notifications while editing the corresponding customer / item / rental.

**Comment by skjerns** [comment]
I have two concepts how we could implement the reminder for people besides the notifications

Version 1: color cell / row, and let user choose a color. This could be implemented both for customers and for items. Advantage: We can use different colors to display different things. Hovering over the cell could show the remark of the item/customer
![image](https://user-images.githubusercontent.com/14980558/103650782-d988ad80-4f60-11eb-9366-d7dd5338af02.png)

Version 2: Show a small exclamation mark, clicking/hovering on exclamation mark will open the issue
![image](https://user-images.githubusercontent.com/14980558/103651098-59167c80-4f61-11eb-8b11-e1f09be3ec41.png)


what do you think?

**Comment by daniel17903** [comment]
I like the colored cells best. When clicking on a highlighted customer_name cell in rentals we could also link to the customer table. Maybe if in the customer table we also highlight cells we might not even need popups.

**Comment by skjerns** [comment]
I've started implementing, and could use `SELECTION` input for it nicely

![image](https://user-images.githubusercontent.com/14980558/104098798-ed078180-529c-11eb-92dc-139bf391992d.png)

It would also not be a problem to highlight things in the customer page&popup, however, I struggle to color the background cell in the rentals tab, as there is no direct connection to the customer-db. I guess querying the highlight-status for each rental row from the customer-table would be quite a workload?

**Comment by daniel17903** [comment]
> I've started implementing, and could use `SELECTION` input for it nicely
> 
> ![image](https://user-images.githubusercontent.com/14980558/104098798-ed078180-529c-11eb-92dc-139bf391992d.png)
> 
> It would also not be a problem to highlight things in the customer page&popup, however, I struggle to color the background cell in the rentals tab, as there is no direct connection to the customer-db. I guess querying the highlight-status for each rental row from the customer-table would be quite a workload? Do you have an alternative idea how this could be solved without too much strain on performance? we would also need to query items-db at some point i guess.

Ah, so you are planning to add a new field like is_highlighted to customers and rentals? Then those rows as well as the corresponding cells in rentals should be highlighted correct?

To highlight rental cells I would edit this rowBackgroundColorFunction so that it can color cells instead of rows here https://github.com/leih-lokal/LeihLokalVerwaltung/blob/53f5760465d2e7729219adeeac7a6bc2ae817f40/Frontend/src/components/TableEditors/Rentals/Rentals.svelte#L27

and here
https://github.com/leih-lokal/LeihLokalVerwaltung/blob/53f5760465d2e7729219adeeac7a6bc2ae817f40/Frontend/src/components/Table/Row.svelte#L50

In the rowBackgroundColorFunction you would need to query the item and customer databases. Row.svelte should already render everything without the color if the database queries did not finish yet. When they finish it could just rerender and add the colors. You could use promises to achieve that (see https://svelte.dev/tutorial/await-blocks).

Feel free to open a PR, even if it is not finished yet, then I can comment on your code and help out.

**Comment by skjerns** [comment]
@daniel17903 this is already live or?

When I just tried it on the github pages, it didn't seem to work - it highlights things in Rentals, but the rows are not highlighted in Customers

**Comment by daniel17903** [comment]
> @daniel17903 this is already live or?
> 
> When I just tried it on the github pages, it didn't seem to work - it highlights things in Rentals, but the rows are not highlighted in Customers

Yes, I think I broke it when I merged it. It will be fixed again with #154
