### ISSUE TITLE
Make visual display more compact

### ISSUE THREAD

**Issue by skjerns** [leih-lokal/LeihLokalVerwaltung#112]
I think we could make the general display of the app more compact, furthermore some parts might be set-able on-the-fly

1. All popups should be optimized such that they fit on one page without scrolling when viewed with the laptop/ipad. I already tried to change flex-wrap to 'column', however this way the order of elements is wrong. I'd love to have something like flex-wrap-column but with order such as row, could not find anything on stackoverflow for that.
2. I suggest reducing `rowHeight` (curr. 40) to a lower value like 26 or 24. This way more values fit on one page and its easier to get a good overview. It also comes closer to the excel interface. I already tried to just change that, but then the page enumerator doesn't seem to display properly. Maybe this could be part of a settings-popup?

What do you guys think @daniel17903 @parttimenerd @christianstarck ?

**Comment by daniel17903** [comment]
1. Yes you are absolutely right. I just haven't spent much time on styling yet.
2. I made it that large so that you can see the images for rentals / items, for lower row heights they are not recognizable. Also everyone should be able to read the text. Do we really need to see more items on one page? You can use the browser zoom to make everything smaller / bigger which also affects the row count displayed per page.
3. We should also only display necessary inputs when creating / editing things. For example when creating a new rental we don't need to display the deposit_returned or returned_on fields.

**Comment by skjerns** [comment]
2. Yes, but this also shrinks the font-size! I though of leaving the font size, but reducing the row heights. At the moment there is a lot of padding above and below the font which could be reduced. But you are right, that would shrink the images...
3. Very good idea! Didn't think of this :) should be rather easy to implement, I'll see if I find time tomorrow

**Comment by daniel17903** [comment]
**Done:**

- Only display necessary fields

**Still Todo:**

- Popup Styling
