### ISSUE TITLE
Infinity scroll

### ISSUE THREAD

**Issue by skjerns** [leih-lokal/LeihLokalVerwaltung#26]
I don't know how hard it is to implement infinity scroll for the pages?

Else maybe a button/setting that lets the user choose how much to display on one page?

**Comment by daniel17903** [comment]
I already tried to implement infinity scroll using [Svelte Virtual List](https://github.com/sveltejs/svelte-virtual-list). I wasn't able to get it 100% working so I switched back to pagination. I still think that infinity scroll would be a better user experience, so if anyone else wants to try it feel free to do so.

At the moment the number of rows displayed on one page is calculated automatically depending on the available space on screen so that scrolling is not necessary. Maybe when can add that setting in the future.
