### ISSUE TITLE
Delete Item / Remove Item from assortment

### ISSUE THREAD

**Issue by christianstarck** [leih-lokal/LeihLokalVerwaltung#96]
The Website Status of an Item is somehow confusing for me.
Available / not available is clear.
But does deleted mean it will be deleted or removed from assortment (aus Sortiment genommen)? 

In my opinion 4 Statuses would be better
- available
- not available
- defective (so users know it will be repaired or they can donate a "new" one)
- deleted (not visible on Website anymore)

**Comment by daniel17903** [comment]
At the moment deleted means that it does not exist on the website anymore. We need another status for defective, thats right. I think we should do:
- Items marked as deleted should not be editable (since they do not exist on the website)
- The state deleted should not be selectable when editing an item (since this can be achieved by pressing the delete button)
- Add a new status for defective and sync that with the correct status on the website
